### ISSUE TITLE
Fix workaround with empty epoch transition

### ISSUE THREAD

**Issue by Nashatyrev** [harmony-dev/beacon-chain-java#100]
The commit https://github.com/harmony-dev/beacon-chain-java/commit/b355f03f8e7f20a6737c4fd6c455a0463f96b9cc fixes an issue, that latest block in an epoch doesn't produce the latest state, i.e. this block is not included in the final epoch transition.
However this fix is rather looks like a workaround. Normally the sequence of states should be the following 
- Empty Slot
- Empty Epoch
- Block state
- Epoch state on top of the block
This should look like a small rebranching from empty epoch state to block based epoch state

Another idea is to emit Epoch state at the time just before the next slot. However this is not a general solution to the problem but rather a convenient representation

**Comment by mkalinin** [comment]
v0.5.1 spec update https://github.com/harmony-dev/beacon-chain-java/pull/113 introduces epoch transition at the beginning of the first slot of next epoch. Which makes this issue outdated.
