### ISSUE TITLE
Fix workaround with ControlledSchedulers

### ISSUE THREAD

**Issue by Nashatyrev** [harmony-dev/beacon-chain-java#101]
The time synchronization issue between controlled schedulers is currently solved by incrementing the time by 1ms each step. 
This can be solved in a more efficient and elegant fashion. Started some work in this branch: https://github.com/harmony-dev/beacon-chain-java/tree/feature/time-controlled

**Comment by mkalinin** [comment]
Solved in https://github.com/harmony-dev/beacon-chain-java/pull/109
