### ISSUE TITLE
Fix optimized `get_shuffling2`

### ISSUE THREAD

**Issue by zilm13** [harmony-dev/beacon-chain-java#106]
1. pull branch `feature/testrunners`
2. activate submodules `git submodule update --recursive --remote`
3. swap files in `resources/eth2.0-tests/shuffling` to uncompressed yml's from attached zip
4. modify `org.ethereum.beacon.test.runner.ShuffleRunner` to use `get_shuffling2`

**expected:** Test `org.ethereum.beacon.test.ShuffleTests.test()` passes.
**actual:** optimized version produces different output compared to original `get_shuffling`

[shuffling.zip](https://github.com/harmony-dev/beacon-chain-java/files/2957500/shuffling.zip)

**Comment by mkalinin** [comment]
Fixed in https://github.com/harmony-dev/beacon-chain-java/pull/112
