### ISSUE TITLE
Tests for InMemoryValidatorRegistryUpdater

### ISSUE THREAD

**Issue by mkalinin** [harmony-dev/beacon-chain-java#11]
### Description
Simply write as much tests as needed to cover functionality of [InMemoryValidatorRegistryUpdater](https://github.com/harmony-dev/beacon-chain-java/blob/initial-state-transition/consensus/src/main/java/org/ethereum/beacon/consensus/state/InMemoryValidatorRegistryUpdater.java) class.

**Comment by Nashatyrev** [comment]
Functionality of this class moved to SpecHelpers
