### ISSUE TITLE
Revisit state tests when merklization is revamped

### ISSUE THREAD

**Issue by mkalinin** [harmony-dev/beacon-chain-java#116]
### Issue 
There is a couple of tweaks have been made in order to complete State tests adoption:
- A few tests have been ignored https://github.com/harmony-dev/beacon-chain-java/blob/5b35e5b8a1aa50b9671015051c4b1a695b53576b/test/src/test/java/org/ethereum/beacon/test/StateTests.java#L22-L25
- Block previous root assertion is commented out https://github.com/harmony-dev/beacon-chain-java/blob/5b35e5b8a1aa50b9671015051c4b1a695b53576b/consensus/src/main/java/org/ethereum/beacon/consensus/spec/BlockProcessing.java#L33-L34

### How to fix
Revisit State tests when following conditions are met:
- SSZ with merklization refactor is finished https://github.com/harmony-dev/beacon-chain-java/pull/115
- `hash_tree_root` tests are adopted and pass https://github.com/ethereum/eth2.0-test-generators/pull/34

**Comment by zilm13** [comment]
guess, it's not actual anymore. There are no such state tests. But we have some proof that our `hash_tree_root` and `signing_root` methods work well
