### ISSUE TITLE
Implement Bytes8 datatype

### ISSUE THREAD

**Issue by mkalinin** [harmony-dev/beacon-chain-java#4]
### Improvement
Add `Bytes8` datatype in a similar to `Bytes32` fashion. And use it as a type of `MessageParameters.domain` field which has `bytes8` datatype according to the spec.

### Rationale
Increases type safety and code readability.

**Comment by Nashatyrev** [comment]
@mkalinin Didn't found any spec description of `MessageParameters.domain` or existing code. Could you point me plz?

**Comment by mkalinin** [comment]
@Nashatyrev here is it https://github.com/harmony-dev/beacon-chain-java/blob/master/crypto/src/main/java/org/ethereum/beacon/crypto/MessageParameters.java#L29

And this section of the spec uses `bytes8` for domain https://github.com/ethereum/eth2.0-specs/blob/master/specs/bls_signature.md#hash_to_g2
