### ISSUE TITLE
Replace Hashable interface implementations with hash_tree_root

### ISSUE THREAD

**Issue by mkalinin** [harmony-dev/beacon-chain-java#64]
### To Do
`hash_tree_root` function is a part of `consensus` module as it is a part of the spec. Hence, core objects like `BeaconBlock`, `BeaconState`, etc. becomes agnostic to hash function. It needs to be reflected in the code.

**Comment by zilm13** [comment]
@mkalinin this issue looks like done by #65

**Comment by mkalinin** [comment]
@zilm13 yep, you're right 👍
