### ISSUE TITLE
Check proof of possession and withdrawal credentials when processing deposits

### ISSUE THREAD

**Issue by mkalinin** [harmony-dev/beacon-chain-java#9]
### What's wrong
Proof of possession and withdrawal credentials are not checked when deposit is being processed.

### Proposal
Proof of possession check should be a part of verification logic, blocks that includes deposits with wrong proofs of possession should be considered as invalid. Initial deposits with wrong proof should be discarded silently with INFO message in the log. 

Withdrawal credentials does make sense only for top ups. Hence, it should be a part of verification logic with same behavior as for proofs of possession.

**Comment by Nashatyrev** [comment]
Block deposits validation is now implemented within `SpecHelpers.process_deposit`
Separate issue regarding initial deposit validation

**Comment by mkalinin** [comment]
Addressed by https://github.com/harmony-dev/beacon-chain-java/pull/98
